site_name: Annyoing's Blog
site_url: https://an-noying.github.io/ANNOYING
site_author: ANNOYING
site_description: >-
  반갑습니다. 종함 게임 정보를 다루는 블로거이자 유튜버지만, 현재는 한국 메이플스토리를 주로 하고 있습니다.

theme:
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.prune
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.tooltips
  language: ko
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: 다크 모드로 전환합니다.

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 라이트 모드로 전환합니다.

copyright: >
  &copy; 2024. ANNOYING all right reserved. –
  <a href="#__consent">쿠키 설정 변경</a>

extra:
  consent:
    actions:
      - accept
      - reject
      - manage
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  analytics:
    provider: google
    property: G-QZD2QJ4W4X
    feedback:
      title: 이 게시물이 도움이 되었나요?
      ratings:
        - icon: material/emoticon-happy-outline
          name: 도움이 되었습니다.
          data: 1
          note: >- 
            피드백 감사합니다.
        - icon: material/emoticon-sad-outline
          name: 도움이 되지 않았어요.
          data: 0
          note: >- 
            피드백 감사합니다!

extra_css:
  - stylesheets/extra.css

plugins:
  - blog:
      blog_toc: true
      blog_dir: MapleStory
      categories_allowed:
        - 안내서
        - 패치 및 업데이트
        - 이벤트
        - 퀘스트
        - 아이템
        - 몬스터
        - 정보
        - 자료실
        - WzComparerR2
      categories_toc: true
      post_url_format: "{file}"
  - search
  - tags
  - glightbox

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - tables
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true